(define (print-fizzbuzz n)
    (if (= 0 (% n 15))
        (println "FizzBuzz")
        (if (= 0 (% n 3))
            (println "Fizz")
            (if (= 0 (% n 5))
                (println "Buzz")
                (println n)
                )
            )
        )
    )

(define (fizzbuzz iter last)
    (while (< iter last)
           (print-fizzbuzz (let iter (+ iter 1)))
        )
    )

(fizzbuzz 1 30)
